### ISSUE TITLE
Undefined Class

### ISSUE THREAD

**Issue by MathiasGilles** [SymfonyCasts/verify-email-bundle#113] opened 2022-03-18 14:55 UTC
Hello, I want to use this bundle on my symfony project. I am on symfony 5.4 and php 8.1.1 but i don't undertand why i have this error. I import those classes, but i don't why i have this error. Can someone have any clues ? 

<img width="757" alt="Screenshot 2022-03-18 at 15 52 45" src="https://user-images.githubusercontent.com/50920505/159026212-c672f946-6f54-4fa4-84f8-c11e5846aee0.png">
<img width="898" alt="Screenshot 2022-03-18 at 15 52 38" src="https://user-images.githubusercontent.com/50920505/159026216-b2a30637-4d7c-4ea4-a2e6-4b364c7398a2.png">

**Comment by ToshY** [comment] 2022-03-19 15:34
@MathiasGilles My first guess is that you stumbled upon the same problem as in #44. Ryan suggests to remove and require  the bundle again, so maybe that helps.

**Comment by bocharsky-bw** [comment] 2022-03-20 17:59
Also, please, clear the cache (probably better with `rm -rf var/cache/`) and try agian. Otherwise, let us know the exact version of the bundle you have installed

**Comment by developers-global21** [comment] 2022-04-04 12:18
I have same problem and confirmation's email don't send

**Comment by eudojosegonzalez** [comment] 2022-04-05 12:08
Thank you very much for your attention.

The problem was caused by an error in the mailing address that was designated for shipments. Sorry to bother.

And again thanks for the answer

**Comment by bocharsky-bw** [comment] 2022-04-05 18:14
@MathiasGilles Could you confirm or refute suggestions here, please? Do you still have this issue?

**Comment by eudojosegonzalez** [comment] 2022-04-06 13:50
The problem is solved, thanks again

**Comment by bocharsky-bw** [comment] 2022-04-06 14:12
OK, I'm closing this issue then. Feel free to reopen if you have the same error but the recommendations in this thread do not help

**Closed by bocharsky-bw** 2022-04-06 14:12 UTC
