### ISSUE TITLE
Missing documentation about "non-verified means not logged" behaviour  

### ISSUE THREAD

**Issue by Yopai** [SymfonyCasts/verify-email-bundle#70] opened 2021-04-08 02:17 UTC
Saying the email is verified is good.

What people generally want is :
don't consider user as logged in if they hasn't verified their email

And I'm afraid a significant portion of them will consider the plugin will add this verification automatically

Even if it is, in fact, out of the scope of this bundle, maybe a warning could be useful to recall you have to handle it (with some links or pointers on to how to do it). (If there is one, I didn't see it)

(which can be simply done by, when getting Roles in User class, adding a VERIFIED_EMAIL role, then checking it, instead of - or in addition to - IS_AUTHENTICATED_FULLY, in firewall and anywhere you use this special role)

**Comment by jrushlow** [comment] 2021-04-08 03:22
Howdy @Yopai -

Duplicate of #38.

https://github.com/SymfonyCasts/verify-email-bundle#anonymous-validation

PR's are always welcome for improvements to our code base & documentation.

>(which can be simply done by, when getting Roles in User class, adding a VERIFIED_EMAIL role, then checking it, instead of - or in addition to - IS_AUTHENTICATED_FULLY, in firewall and anywhere you use this special role)

Unfortunately, Authorization is outside the scope of this bundle - as is Authentication. Symfony does however provide some pretty cool tools to implement your own authorization strategies, more info on how to do so can be found https://symfony.com/doc/current/security.html

**Closed by jrushlow** 2021-04-08 03:22 UTC
Labels: duplicate
