### ISSUE TITLE
validation works only when user is connected

### ISSUE THREAD

**Issue by Nizar-bouraoui** [SymfonyCasts/verify-email-bundle#33] opened 2020-07-30 12:03 UTC
how can make validation even when user is not connected

**Comment by MatTheCat** [comment] 2020-07-30 15:27
Duplicate of https://github.com/SymfonyCasts/verify-email-bundle/issues/27

**Comment by jrushlow** [comment] 2020-07-31 03:50
same as #27

**Closed by jrushlow** 2020-07-31 03:50 UTC
Labels: duplicate
